spring:
  application:
    name: turbine
turbine:
  aggregator:
    cluster-config: default
  app-config: product-view-service-feign
  cluster-name-expression: new String("default")
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/