spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/maximusyoung007/springCloudDemo
          searchPaths: springcloudConfig/respo
euraka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/