spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://gitee.com/maximusyoung007/spring-cloud-demo
          searchPaths: respo
euraka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/